<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_medicos  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeQueryList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, &$pageObject)
{

		// Tu consulta completa, incluyendo JOIN y ORDER BY
    $strSQL = "SELECT
        m.id_medico,
        CONCAT(m.nombre, ' ', m.apellido) AS medico_nombre_completo,
        CONCAT('Dr. ', m.nombre, ' ', m.apellido) AS medico_con_titulo,
        e.id_especialidad,
        e.nombre AS especialidad,
        m.telefono,
        m.email,
        m.activo
    FROM medicos m
    JOIN especialidades e ON m.id_especialidad = e.id_especialidad";

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
